# Generated by Django 5.2.8 on 2025-12-01 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Letter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_index", models.PositiveSmallIntegerField(unique=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("text", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="DialogueNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_index", models.PositiveSmallIntegerField()),
                (
                    "speaker",
                    models.CharField(
                        choices=[
                            ("cat", "Cat"),
                            ("user", "User"),
                            ("system", "System"),
                        ],
                        default="cat",
                        max_length=10,
                    ),
                ),
                ("text", models.TextField()),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        help_text="Порядок реплики внутри дня"
                    ),
                ),
            ],
            options={
                "ordering": ["day_index", "order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("day_index", "order"), name="unique_day_index_for_order"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AnswerOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                (
                    "is_end",
                    models.BooleanField(
                        default=False,
                        help_text="Если true — после этого ответа сцена заканчивается",
                    ),
                ),
                (
                    "dialogue_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="api.dialoguenode",
                    ),
                ),
                (
                    "next_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incoming_options",
                        to="api.dialoguenode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chosen_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.answeroption",
                    ),
                ),
                (
                    "dialogue_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.dialoguenode",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserDayProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_index", models.PositiveSmallIntegerField()),
                ("scene_completed", models.BooleanField(default=False)),
                ("letter_opened", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="day_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "day_index"), name="Unique day_index for user"
                    )
                ],
            },
        ),
    ]
